### PR TITLE
forbid the deletion of global and system

### LINKED ISSUE #236: Bug: Namespace `global` and `system` can be deleted
**Describe the bug**
The namespace `global` and `system` can be deleted but it shouldn't be allowed.

**To Reproduce**
Run:
```bash
nanocl namespace rm global
```
When no cargoes are created in the global namespace.

**Expected behavior**
This should return an error maybe a `401` because if both of this namespace doesn't exist it can cause unexpected behavior.

This is just a daemon/api change.

### PR DESCRIPTION
**Pull request by n0tank3sh**
fixes #236

### CODE REVIEW

File: bin/nanocld/src/services/namespace/delete.rs [hunk 1]
```diff
@@ -1,6 +1,6 @@
-use ntex::web;
+use ntex::web::{self};
```
Comment (0xle0ne) [inline bin/nanocld/src/services/namespace/delete.rs]: We don't need the ::{self} there

File: bin/nanocld/src/services/namespace/delete.rs [hunk 2]
```diff
@@ -18,13 +18,19 @@ use crate::{
   responses(
     (status = 202, description = "Namespace have been deleted"),
     (status = 404, description = "Namespace is not existing", body = crate::services::openapi::ApiError),
+    (status = 401, description = "Deletion of this namespace is forbidden", body = crate::services::openapi::ApiError),
```
Comment (0xle0ne) [inline bin/nanocld/src/services/namespace/delete.rs]: Forbidden is 403

**Review by 0xle0ne — CHANGES_REQUESTED** [review]

**Comment by 0xle0ne** [comment]
Can you add a changelog entry pls? with just [untagged] version for now.
You can add a link to our profile in the changelog

**Comment by 0xle0ne** [comment]
Also you should write tests for that to not loose coverage pls, there are located there:

https://github.com/next-hat/nanocl/blob/nightly/bin/nanocld/src/services/namespace/mod.rs

File: bin/nanocld/src/services/namespace/delete.rs (hunk 1 above)
Comment (n0tank3sh) [reply bin/nanocld/src/services/namespace/delete.rs]: Done

File: bin/nanocld/src/services/namespace/delete.rs (hunk 2 above)
Comment (n0tank3sh) [reply bin/nanocld/src/services/namespace/delete.rs]: My bad, fixed it

File: bin/nanocld/src/services/namespace/mod.rs [hunk 3]
```diff
@@ -82,6 +82,22 @@ mod test_namespace {
...
   }
+  async fn forbidden_delete(client: &TestClient) {
+    let global_del_res = client
+      .send_delete(&format!("{ENDPOINT}/global"), None::<String>)
+      .await;
+    let system_del_res = client
+      .send_delete(&format!("{ENDPOINT}/system"), None::<String>)
+      .await;
+    assert!(
+      global_del_res.status().as_str() == "403",
```
Comment (0xle0ne) [inline bin/nanocld/src/services/namespace/mod.rs]: Use ntex::http::StatusCode instead with assert_eq! macro:
```rust
assert_eq!(res.status, http::StatusCode::FORBIDDEN, "expect deletion of global namespace to be forbidden");
```

File: bin/nanocld/src/services/namespace/mod.rs [hunk 4]
```diff
@@ -82,6 +82,22 @@ mod test_namespace {
...
+      "Expect deletion of global namespace to be forbidden"
+    );
+    assert!(
```
Comment (0xle0ne) [inline bin/nanocld/src/services/namespace/mod.rs]: same there

**Review by 0xle0ne — CHANGES_REQUESTED** [review]

**Comment by 0xle0ne** [comment]
You should add a link to your profile on the changelog like this:

```
by [n0tank3sh](https://github.com/n0tank3sh)
```

**Comment by n0tank3sh** [comment]
@leon3s I have made the changes as requested.

**Review by 0xle0ne — APPROVED** [review]
Thanks!

**Comment by n0tank3sh** [comment]
oh man really, lemme fix it !!

**Comment by 0xle0ne** [comment]
What happened ?

**Comment by n0tank3sh** [comment]
no worries, I got it. Just I tried to sign my commits because it was blocking due to unverified commits. I didn't add gpg key of the pc I am using. xd. During the rebase for squashing (likely picked the wrong number of commits) something happened. I will apply the diff to nightly than squash and verify the commits.

**Comment by n0tank3sh** [comment]
fixed it xd. I shouldn't make these type of mistakes. I am really sorry

**Review by 0xle0ne — APPROVED** [review]
